#rireetchanson
p_rireetchansons:
    pattern:  /rireetchansons/
    host:     "{domain}"
    defaults:
        _controller: SkreenHouseFactoryPartnersBundle:rireetchansons:main
        domain: myskreen.rireetchansons.fr
    requirements:
        domain: myskreen\.rireetchansons\.fr|preprod-v3\.myskreen\.com|v3\.(.*)\.myskreen\.typhon\.net
#programmetvcom
p_programmetvcom:
    pattern:  /programmetvcom/
    host:     "{domain}"
    defaults:
        _controller: SkreenHouseFactoryPartnersBundle:programmetvcom:main
        domain: programme-tv.com
    requirements:
        domain: replay\.programme-tv\.com|preprod-v3\.myskreen\.com|v3\.(.*)\.myskreen\.typhon\.net
p_programmetvcom_home:
    pattern:  /programmetvcom/{home}/
    defaults:
        _controller: SkreenHouseFactoryPartnersBundle:programmetvcom:main
        domain: replay.programme-tv.com
    requirements:
        domain: replay\.programme-tv\.com|preprod-v3\.myskreen\.com|v3\.(.*)\.myskreen\.typhon\.net
#directmatin
p_directmatin:
    pattern:  /directmatin/
    defaults:
        _controller: SkreenHouseFactoryPartnersBundle:directmatin:main
        domain: replay.directmatin.fr
    requirements:
        domain: replay\.directmatin\.fr|preprod-v3\.myskreen\.com|v3\.(.*)\.myskreen\.typhon\.net
#directmatin selection
p_directmatin_selection:
    pattern:  /directmatin/{homeslug}/selection/{id}-{slug}/
    defaults:
        _controller: SkreenHouseFactoryV3Bundle:Content:selection
        partner: DirectMatin
        domain: replay.directmatin.fr
    requirements:
        domain: replay\.directmatin\.fr|preprod-v3\.myskreen\.com|v3\.(.*)\.myskreen\.typhon\.net
        id: \d+
        slug: "[^/]+"
        homeslug: "[^/]+"
#leparisien
p_leparisien:
    pattern:  /leparisien/
    host:     "{domain}"
    defaults:
        _controller: SkreenHouseFactoryPartnersBundle:leparisien:main
        domain: leparisien.fr
    requirements:
        domain: leparisien\.fr|preprod-v3\.myskreen\.com|v3\.(.*)\.myskreen\.typhon\.net
#liberation
p_liberation:
    pattern:  /liberation/
    host:     "{domain}"
    defaults:
        _controller: SkreenHouseFactoryPartnersBundle:liberation:main
        domain: liberation.fr
    requirements:
        domain: liberation\.fr|preprod-v3\.myskreen\.com|v3\.(.*)\.myskreen\.typhon\.net