#rireetchanson
p_rireetchansons:
    pattern:  /rireetchansons/
    defaults: { _controller: SkreenHouseFactoryPartnersBundle:rireetchansons:main }
#leparisien
p_leparisien:
    pattern:  /leparisien/
    defaults: { _controller: SkreenHouseFactoryPartnersBundle:leparisien:main }
#liberation
p_liberation:
    pattern:  /liberation/
    defaults: { _controller: SkreenHouseFactoryPartnersBundle:liberation:main }
#programmetvcom
p_programmetvcom:
    pattern:  /programmetvcom/
    defaults: { _controller: SkreenHouseFactoryPartnersBundle:programmetvcom:main }
p_programmetvcom_home:
    pattern:  /programmetvcom/{home}
    defaults: { _controller: SkreenHouseFactoryPartnersBundle:programmetvcom:main }
#directmatin
p_directmatin:
    pattern:  /directmatin/
    defaults: { _controller: SkreenHouseFactoryPartnersBundle:directmatin:main }
#directmatin selection
p_directmatin_selection:
    pattern:  /directmatin/{homeslug}/selection/{id}-{slug}/
    defaults: { _controller: SkreenHouseFactoryV3Bundle:Content:selection, partner: DirectMatin }
    requirements:
        id: \d+
        slug: "[^/]+"
        homeslug: "[^/]+"